### ISSUE TITLE
Unicode distinction between white and black color pieces can be enhanced for FAN notation

### ISSUE THREAD

**Issue by KartikWatts** [chesslablab/js-utils#44]
In the current Figurine Algebraic Notation (FAN) conversion, I see the Unicode is kept the same for both white and black pieces, while in Unicode we have different characters for all the pieces for white and black colors, in my opinion having the distinction would be better.

Reference for Unicode chess symbols: https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode#The_basic_12_chess_pieces

Example: `Movetext.toFan()` method for a `movetext` string: **"1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Qa5+ 5.Qd2"** 

Current FAN conversion: **1.e4 c5 2.♘f3 ♘c6 3.d4 cxd4 4.♘xd4 ♕a5+ 5.♕d2**

Expected FAN conversion: **1.e4 c5 2.♘f3 ♞c6 3.d4 cxd4 4.♘xd4 ♛a5+ 5.♕d2**

Right now the conversion is as per logic:
``` js
str = str.replaceAll('R', '♖');
str = str.replaceAll('N', '♘');
str = str.replaceAll('B', '♗');
str = str.replaceAll('Q', '♕');
str = str.replaceAll('K', '♔');
```

Instead, we could use enhanced logic to have better Unicodes like:
```php
private const WHITE_PIECES = [
        'N' => '♘', // White Knight
        'B' => '♗', // White Bishop
        'R' => '♖', // White Rook
        'Q' => '♕', // White Queen
        'K' => '♔', // White King
    ];
    
private const BLACK_PIECES = [
    'N' => '♞', // Black Knight
    'B' => '♝', // Black Bishop
    'R' => '♜', // Black Rook
    'Q' => '♛', // Black Queen
    'K' => '♚', // Black King
];
 ```
 
As I am already working on a similar implementation for php-chess: https://github.com/chesslablab/php-chess/issues/487, I'll share more details and discussion there with draft PR and if you feel the same, I can work on enhancement here as well, let me know your thoughts on this @programarivm. Regards.

**Comment by programarivm** [comment]
@KartikWatts this is a good point. Mainstream platforms also stick with using the white pieces for the FAN notation.

**Comment by KartikWatts** [comment]
@programarivm Got it, so we can keep it the same as existing. Closing the issue.
